config/routes.rb
Rails.application.routes.draw do
  # get 'welcomes/index'
  # root 'welcomes#index'
  root 'students#index'
 

  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

class Student < ApplicationRecord
  
end

app/models/student.rb
class Student < ApplicationRecord
	validates :first_name, :last_name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
   before_action :set_student, only: %i[show edit update destroy] 

	def index
	 @students = Student.all
	end

	def new
	 @student = Student.new
	end

	def create
     @student = Student.new(student_params)
	  if @student.save
	  	 redirect_to students_path, notice: "Student has been created successfully"
	  else
	  	 render :new, status: :unprocessable_entity
	  end
	end

	def show
	 # @student = Student.find(params[:id])
	end

	def edit
	 # @student = Student.find(params[:id])
	end

	def update
	 # @student = Student.find(params[:id])
	 if @student.update(student_params)
	 	 redirect_to @student, notice: "Student has been updated successfully"
	 else
	 	 render :edit, status: :unprocessable_entity
	 end
	end

	def destroy
	 # @student = Student.find(params[:id])
	 @student.destroy

	 redirect_to @student, status: :see_other, notice: "Student has been deleted successfully"
	end

	private
	def student_params
	  params.require(:student).permit(:first_name, :last_name, :email)
	end

	def set_student
	 @student = Student.find(params[:id])
	end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentMgmt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <%= render 'welcomes/header' %>
    </div>
    <%= yield %>
    <div>
      <%= render 'welcomes/footer' %>
    </div>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with model: student do |form| %>
 <div>
     <%= form.label :first_name %><br>
     <%= form.text_field :first_name %>
     
     <% @student.errors.full_messages_for(:first_name).each do |message| %>
        <div><%= message %></div>
     <% end %>
 </div>
 <div>
 	 <%= form.label :last_name %><br>
 	 <%= form.text_field :last_name %>

     <% @student.errors.full_messages_for(:last_name).each do |message| %>
         <div><%= message %></div>
     <% end %>
 </div>
 <div>
    <%= form.label :email %><br>
    <%= form.email_field :email %>

    <% @student.errors.full_messages_for(:email).each do |message| %>
 <div><%= message %></div>
     <% end %>
 </div><br>
 <div>
 	 <%= form.submit %>
 </div>
<% end %>

app/views/students/edit.html.erb
<p><%= notice %></p>
<h1>Edit Student</h1>
<%= render 'form', student: @student %>

app/views/students/index.html.erb
<%= stylesheet_link_tag "custom" %>
<div class="container">
	<div>
		
	</div>
   <div>
		<p><%= notice %></p>
		<h1 class="xyz">List of Students</h1>
		<%= link_to 'New Student', new_student_path %>
		<table>
			<thead>
				<tr>
					<th>First Name</th>
					<th>Last Name</th>
					<th>Email</th>
					<th colspan="3">Actions</th>
				</tr>
			</thead>
			<tbody>
				<% @students.each do |student| %>
				 <tr>
				 	<td><%= student.first_name %></td>
		            <td><%= student.last_name %></td>
				 	<td><%= student.email %></td>
			        <td><%= link_to 'View', student %></td>
				    <td><%= link_to 'Edit', edit_student_path(student) %></td>
				 	<td><%= link_to "Delete", student, data: {
			          turbo_method: :delete, turbo_confirm: "Are you sure"} %>
		            </td>
				 </tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/students/new.html.erb
<%= stylesheet_link_tag "custom" %>
<h1 class="tree">New Student</h1>

<%= render "form", student: @student %>

app/views/students/show.html.erb
<p><%= notice %></p>
<h1>Student Details</h1>

<p><strong>First Name : <%= @student.first_name %></strong></p>
<p><strong>Last Name : <%= @student.last_name %></strong></p>
<p><strong>Email : <%= @student.email %></strong></p>

<%= link_to 'Back', students_path %> |
<%= link_to 'Edit', edit_student_path(@student) %>

app/views/welcomes/_header.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">Home</a>
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/welcomes/index.html.erb
<h1>Nagendra</h1>